### ISSUE TITLE
Login error from time to time

### ISSUE THREAD

**Issue by moshere** [mgp25/WhatsAPI-Official#350]
Hi,
I'm running pollmessages in a loop and from time to time (every 2-3 hours) I'm getting such message.
Can you relate to it? Is there any way to eliminate it?

Thank you,
Moshe

```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="********">T???**********?????:gR?4IQnT?+?,??1423137614WhatsApp/2.12.60 S40Version/14.26
Device/Nokia302 MccMnc/425001</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>
```
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Login Failure' in C:\WhatsAPI-Official-master\src\whatsprot.class.p
hp:2276
Stack trace:
#0 C:\WhatsAPI-Official-master\src\whatsprot.class.php(603): WhatsProt->doLogin()
#1 C:\WhatsAPI-Official-master\src\whatsapp_whatsapi_recieve.php(17): WhatsProt->loginWithPassword('/uyFduKIIVpmZPp...')
#2 {main}
  thrown in C:\WhatsAPI-Official-master\src\whatsprot.class.php on line 2276
```

**Comment by mgp25** [comment]
@moshere this is caused only when logging in and not with polling messages, this is related to a connectivity issue, when you didn't login successfully to WhatsApp, be sure your signal strength is right and try again.

Regards

**Comment by moshere** [comment]
Thank you. Is it WhatsApp issue?

**Comment by mgp25** [comment]
@moshere connectivity issue. Not an issue at all
