### ISSUE TITLE
Massive problems in connecting

### ISSUE THREAD

**Issue by theArch2** [mgp25/WhatsAPI-Official#449]
Hi, since yesterday evening i have massive connection-problems to whatsapp.
The connection of my server itself is fine.

i get stacktraces like this:

```

PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Tree length did not match received length (buff = 1 & treeLength = 66)' in /wa/var/src/whatsprot.class.php:3673
Stack trace:
#0 /wa/var/src/whatsprot.class.php(587): WhatsProt->readStanza()
#1 /wa/var/src/whatsprot.class.php(2054): WhatsProt->pollMessage()
#2 /wa/var/src/whatsprot.class.php(3753): WhatsProt->waitForServer(NULL)
#3 /wa/var/src/whatsprot.class.php(718): WhatsProt->sendBroadcast(Array, Object(ProtocolNode), 'text')
#4 /wa/var/ownFunc/functions.php(1216): WhatsProt->sendBroadcastMessage(Array, 'Blitzer Hachm??...')
#5 /wa/var/examples/exampleFunctional.php(154): processBroadcastQueue()
#6 {main}
```

and loginFailures and readStanze-Exceptions and so on...

someone noticed this?

edit:

see 
```
PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Failed to read stanza header' 
```

**Comment by mgp25** [comment]
@theArch2 this is caused because you are trying to send massive broadcasts
