### ISSUE TITLE
PHP Fatal error:

### ISSUE THREAD

**Issue by sant527** [mgp25/WhatsAPI-Official#483]
I am trying to send an image to 2 persons i get the following error.

Some times it happens and sometimes it doesnot. How to understand this

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Login Failure' in /home/simha/.public_html/.whatsappapi/WhatsAPI-Official/src/whatsprot.class.php:2308
Stack trace:
#0 /home/simha/.public_html/.whatsappapi/WhatsAPI-Official/src/whatsprot.class.php(561): WhatsProt->doLogin()
#1 /home/simha/.public_html/.whatsappapi/Broadcast_friends.php(43): WhatsProt->loginWithPassword('djsdksjdksjdsd....')
#2 {main}
  thrown in /home/simha/.public_html/.whatsappapi/WhatsAPI-Official/src/whatsprot.class.php on line 2308
```

**Comment by mgp25** [comment]
Post your code and debug log
