### ISSUE TITLE
Unable to access account

### ISSUE THREAD

**Issue by seekshiva** [mgp25/WhatsAPI-Official#597]
Hi

First of all, thanks for building this awesome tool!

I had called the `registerTool.php` script to obtain password for my mobile number. With the user fromNumber and waPassword fields set, I was able to send and receive messages.

I wanted to run the script on a server rather than my laptop, so I cloned the official repo; scp'd my php file. (I did not know then that wadata/id.&lt;mob-no&gt;.dat needed to be copied too)

Since the wadata directory in my server was empty, WhatsProt generated a new random string for my id.&lt;mob-no&gt;.dat file. And so, I got this:

```
PHP Fatal error:  Uncaught exception 'LoginFailureException' in /<path>/WhatsAPI-Official/src/whatsprot.class.php:2304
Stack trace:
#0 /<path>/WhatsAPI-Official/src/whatsprot.class.php(562): WhatsProt->doLogin()
#1 /<path>/WhatsAPI-Official/examples/sendMessage.php(456): WhatsProt->loginWithPassword('jR4LChIR+2wXA7q...')
#2 /<path>/WhatsAPI-Official/examples/sendMessage.php(511): Whatsapp->connectToWhatsApp()
#3 /<path>/WhatsAPI-Official/examples/sendMessage.php(372): Whatsapp->sendMessage('<recepient-number>', 'hi\n')
#4 /<path>/WhatsAPI-Official/examples/sendMessage.php(281): Whatsapp->process('<recepient-number>', 'hi\n')
#5 {main}
  thrown in /home/shiva/bot/WhatsAPI-Official/src/whatsprot.class.php on line 2304
```

Now, back in my laptop, when I run the script, I get:
```
Fatal error:  Uncaught exception 'LoginFailureException' in /<path>/WhatsAPI-Official/src/whatsprot.class.php:2304
Stack trace:
#0 /<path>/WhatsAPI-Official/src/whatsprot.class.php(562): WhatsProt->doLogin()
#1 /<path>/WhatsAPI-Official/examples/whatsapp.php(508): WhatsProt->loginWithPassword('jR4LChIR+2wXA7q...')
#2 /<path>/WhatsAPI-Official/examples/whatsapp.php(623): Whatsapp->connectToWhatsApp()
#3 /<path>/WhatsAPI-Official/examples/whatsapp.php(413): Whatsapp->sendMessage()
#4 /<path>/WhatsAPI-Official/examples/whatsapp.php(283): Whatsapp->process()
#5 {main}
  thrown in /<path>/WhatsAPI-Official/src/whatsprot.class.php on line 2304
```

Then I called `checkCredentials()` to reset my password and got this:

```
Fatal error: Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /<path>/WhatsAPI-Official/src/whatsprot.class.php:198
Stack trace:
#0 /<path>/WhatsAPI-Official/examples/sendMessage.php(310): WhatsProt->checkCredentials()
#1 /<path>/WhatsAPI-Official/examples/sendMessage.php(265): Whatsapp->__construct(Array)
#2 {main}
  thrown in /<path>/WhatsAPI-Official/src/whatsprot.class.php on line 198
```

**Comment by mgp25** [comment]
@seekshiva post your code and debug log

**Comment by seekshiva** [comment]
@mgp25 my sendMessage.php is a mild modification to examples/whatsapp.php. it obtains the mobile number as a command-line argument, and the message is read via STDIN.

```
$whatsapp = new Whatsapp($config);

if(sizeof($argv) == 2) {
    $username = $argv[1];
}
else {
    exit("Usage:\n\tphp sendMessage.php <phone number without + or 00>\n\n");
}

$message = "";
while(($line = fgets(STDIN)) !== false) {
    $message .= $line;
}
$whatsapp->process($username, $message);
```

I'm sorry I haven't developed in php in a long while now - where do I find the debug logs?

**Comment by mgp25** [comment]
@seekshiva You are using outdated code, download latest code of WhatsAPI Official, and follow examples and wiki.

Regards

**Comment by seekshiva** [comment]
@mgp25 I have the latest code:
```
$ git log
commit b156924022a0dcf5b88f70e1e58780c0d76b3669
Author: mgp25 <me@mgp25.com>
Date:   Fri Apr 10 01:06:34 2015 +0200

    Little improvements :)
    
    @0xtrycatch rocks :D

commit 5f02c5ef0cf708f884b8ff1d4f3a5ac8d7ccc7cf
...
...
```

**Comment by mgp25** [comment]
@seekshiva Download the whole source not only the latest commit, if you are getting:

```
Array
(
    [cc] => 91
    [in] => <my-number>
    [id] => ?)u??@???5r?,??w?
    [lg] => hi
    [lc] => IN
    [network_radio_type] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => blocked
)
```

You have an outdated source

**Comment by seekshiva** [comment]
I cloned the WhatsAPI-Official repo to my local machine; that is the code I'm running now. Is there something in the source which is not part of the repo?

**Comment by mgp25** [comment]
@seekshiva 

**UPDATE:** Sorry, i have checked the code, you have latest code. Your number its blocked.

```
stdClass Object
(
    [status] => fail
    [reason] => blocked
)
```

Regards

**Comment by seekshiva** [comment]
Thanks

**Comment by morseslaw0402** [comment]
how to make the whatsapp api work?
And how to find the source code and simple?
